version: '3.8'

networks:
  backend_network:
    driver: bridge

services:

  # ---------- PostgreSQL ----------
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: portfolio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- Redis ----------
  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - backend_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- Zookeeper ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- Kafka ----------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    networks:
      - backend_network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- Backend ----------
  backend:
    image: ksvitlana/portfolio-backend-backend:latest
    env_file:
      - ./portfolio-backend/.env
    ports:
      - "8080:8080"
    networks:
      - backend_network
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
      - redis

  # ---------- Frontend ----------
  frontend:
    image: ksvitlana/portfolio-backend-frontend:latest
    env_file:
      - ./portfolio-frontend/.env
    ports:
      - "3000:80"
    networks:
      - backend_network
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
