services:
  nginx:
    image: nginx:alpine
    container_name: root-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - backend_network

  # ---------- Backend ----------
  backend:
    image: ksvitlana/portfolio-backend-backend:latest
    container_name: root-backend-1
    env_file:
      - /root/.env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      backend_network:
        aliases:
          - backend
    expose:
      - "8080"  # expose порт для Nginx внутри сети
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
      - redis

  # ---------- Frontend ----------
  frontend:
    image: ksvitlana/portfolio-frontend:v1.0.24
    container_name: root-frontend-1
    env_file:
      - /root/.env
    networks:
      backend_network:
        aliases:
          - frontend
    build:
      context: ./portfolio-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://svitlana-kashkina.com/api
    expose:
      - "80"  # expose порт для Nginx внутри сети
    restart: unless-stopped
    depends_on:
      - backend

  # ---------- PostgreSQL ----------
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: portfolio_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - backend_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- Redis ----------
  redis:
    image: redis:7
    container_name: root-redis-1
    env_file:
      - /root/.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    volumes:
      - redis_data:/data
    networks:
      - backend_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5

  # ---------- Zookeeper ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: root-zookeeper-1
    env_file:
      - /root/.env
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    ports:
      - "2181:2181"
    networks:
      - backend_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "echo srvr | nc -w 5 127.0.0.1 ${ZOOKEEPER_CLIENT_PORT} | grep -q 'Mode' || exit 1" ]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

  # ---------- Kafka ----------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: root-kafka-1
    depends_on:
      - zookeeper
    env_file:
      - /root/.env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - backend_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092", "timeout 2 bash -c 'cat < /dev/tcp/localhost/9092 >/dev/null 2>&1' || exit 1" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 6

networks:
  backend_network:
    external: true

volumes:
  postgres_data:
  redis_data:

